version: '3.7'
services:
  frontend:
    ports:
      - '35729:35729'
      - '4200:4200'
    volumes:
      - $PWD/frontend:/frontend
      - /frontend/node_modules
  backend:
    build:
      context: ./backend
    command:
      - /bin/sh
      - -c
      - |
        ./setup.sh
        ./manage.py runserver 0.0.0.0:8000
    volumes:
      - $PWD/backend:/backend
    ports:
      - "8000:8000"
